#! /bin/sh
# script to add a dns zone

RANDOM=$$

if [ `id -u` -ne 0 ]; then
    echo "You must be root to run this script"
    exit 1
fi

# use the first argument as the domain name
if [ -z "$1" ]; then
    echo "Usage: ./dns_add_zone domainname"
    exit 1
fi



# add the zone to config file
echo "zone $1.jaan-lavaerts.sb.uclllabs.be {
        type master;
        file \"/etc/bind/zones/mrt-zones/db.$1.jaan-lavaerts.sb.uclllabs.be\";
    };" >> /etc/bind/named.conf.mrt-zones

# create the zone file
touch /etc/bind/zones/mrt-zones/db.$1.jaan-lavaerts.sb.uclllabs.be

# add the zone to the zone file
echo "\$TTL 604800
@       IN      SOA     ns.$1.jaan-lavaerts.sb.uclllabs.be. root.jaan-lavaerts.sb.uclllabs.be. (
                        69              ; Serial
                        604800          ; Refresh
                        86400           ; Retry
                        2419200         ; Expire
                        604800 )        ; Negative Cache TTL

@       IN      NS      ns.jaan-lavaerts.sb.uclllabs.be.
@       IN      A       193.191.177.158" >> /etc/bind/zones/mrt-zones/db.$1.jaan-lavaerts.sb.uclllabs.be

# add to main zone file
echo "$1     IN      NS      ns.jaan-lavaerts.sb.uclllabs.be." >> /etc/bind/zones/forward.jaan-lavaerts.sb.uclllabs.be
echo "$1     IN      A       193.191.177.158" >> /etc/bind/zones/forward.jaan-lavaerts.sb.uclllabs.be

perl -i -pe '/Serial/ && s/(\d+)/$1+1 . $2/e' /etc/bind/zones/forward.jaan-lavaerts.sb.uclllabs.be

systemctl restart bind9
systemctl restart named
