#! /bin/bash

# This script adds a DNS record to a zone file

RANDOM=$$

if [ `id -u` -ne 0 ]; then
    echo "You must be root to run this script"
    exit 1
fi

# check if -t is used as argument
if [ "$1" = "-t" ]; then

    # check if $2 equals A or CNAME or MX
    if [ "$2" = "A" ]; then
        echo "$3        IN      A       $4" >> /etc/bind/zones/mrt-zones/db.$5
        perl -i -pe "/Serial/ && s/(\d+)/$RANDOM/e" /etc/bind/zones/mrt-zones/db."$5"
        
    fi
    if [ "$2" = "MX" ]; then
        echo "@        IN      MX      $3.$5" >> /etc/bind/zones/mrt-zones/db.$5
        echo "$3        IN      A       $4" >> /etc/bind/zones/mrt-zones/db.$5
        perl -i -pe "/Serial/ && s/(\d+)/$RANDOM/e" /etc/bind/zones/mrt-zones/db."$5"

    fi
    if [ "$2" = "CNAME" ]; then
        echo "$3        IN      CNAME   $4" >> /etc/bind/zones/mrt-zones/db.$4
        perl -i -pe "/Serial/ && s/(\d+)/$RANDOM/e" /etc/bind/zones/mrt-zones/db."$4"

    fi
else
    echo "$1        IN      A       $2" >> /etc/bind/zones/mrt-zones/db.$3
    perl -i -pe "/Serial/ && s/(\d+)/$RANDOM/e" /etc/bind/zones/mrt-zones/db."$3"
fi

systemctl restart bind9
systemctl restart named
