#! /bin/sh

if [ `id -u` -ne 0 ]; then
    echo "You must be root to run this script."
    exit 1
fi

# create a new vhost using $1
if [ -z "$1" ]; then
    echo "Usage: $0 <vhost>"
    exit 1
fi

if [ -d "/var/www/$1" ]; then
    echo "Vhost already exists."
    exit 1
fi

mkdir -p /var/www/$1
mkdir -p /var/www/$1/logs
mkdir -p /var/www/$1/public_html

# make virtual host config file
echo "<VirtualHost *:80>
    ServerName $1
    DocumentRoot /var/www/$1/public_html
    ErrorLog /var/www/$1/logs/error.log
    CustomLog /var/www/$1/logs/access.log combined
</VirtualHost>" > "/etc/apache2/sites-available/$1.conf"

# write index.html
cat > /var/www/$1/public_html/index.html << EOF
<p>welcome $1</p>
EOF


a2ensite $1
service apache2 restart
